name: DEPLOY
env:
  VERSION_TAG: ${{github.ref_name == 'main' && 'latest' || github.ref_name}}
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_BOT_USER }}
          password: ${{ secrets.QUAY_BOT_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/kubevirt-ui/kubevirt-proxy-data:${{env.VERSION_TAG}}
